<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findAllJoinCategory()
    {
        return $this->createQueryBuilder('p')
            ->select(['p', 'c'])
            ->innerJoin('p.category', 'c')
            ->getQuery()
            ->getResult();
    }
}
